name: Complex

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date

  windows:
    runs-on: windows-latest
    needs: ubuntu
    steps:
      - name: Check if Key Vault Exists
        id: check_keyvault  # Define an ID to access outputs later
        shell: pwsh
        run: |
          if ($true) {  # Replace with your condition
            echo "::set-output name=resourceExists::true"
          } else {
            echo "::set-output name=resourceExists::false"
          }

      - run: date

      - name: Display Key Vault Properties
        shell: pwsh
        run: |
          Write-Output "Key Vault Properties:"
          Write-Output "test properties"

      - name: Infrastructure Functions - Create Key Vault
        shell: pwsh
        run: |
          if ('${{ steps.check_keyvault.outputs.resourceExists }}' -eq 'false') {
            Write-Output "Creating Key Vault..."
            # Add key vault creation logic here
          } else {
            Write-Output "Key Vault already exists, skipping creation."
          }

      - name: Display Key Vault Resource Existence Status
        shell: pwsh
        run: |
          Write-Output "resourceExists:"
          Write-Output "${{ steps.check_keyvault.outputs.resourceExists }}"

  macos:
    runs-on: macos-latest
    needs: [ubuntu, windows]
    steps:
      - run: date
