name: Complex

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date

  windows:
    runs-on: windows-latest
    needs: ubuntu  # Run windows after ubuntu
    steps:
      - name: Check if Key Vault Exists
        shell: pwsh
        run: |
          Write-Host "##vso[task.setvariable variable=resourceExists]true"
      - run: date
      - name: Display Key Vault Properties
        shell: pwsh
        run: |
          Write-Output "Key Vault Properties:"
          Write-Output "test properties"

  infrastructure:
    runs-on: windows-latest
    needs: [ubuntu, windows]  # Runs after ubuntu and windows
    strategy:
      runOnce:
        deploy:
          steps:
            - name: Display Key Vault Properties
              shell: pwsh
              run: |
                Write-Output "resourceExists:"
                Write-Output "$env:resourceExists"

  macos:
    runs-on: macos-latest
    needs: [ubuntu, windows, infrastructure]  # Runs after all other jobs
    steps:
      - run: date
