name: Complex

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date

  windows:
    runs-on: windows-latest
    needs: ubuntu  # Run windows after ubuntu
    steps:
      - name: Check if Key Vault Exists
        shell: pwsh
        run: |
          Write-Host "##vso[task.setvariable variable=resourceExists]true"
      - run: date
      - name: Display Key Vault Properties
        shell: pwsh
        run: |
          Write-Output "Key Vault Properties:"
          Write-Output "test properties"

  macos:
    runs-on: macos-latest
    needs: [ubuntu, windows]  # Run macos after ubuntu and windows
    steps:
      - run: date
