name: Complex

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date

  windows:
    runs-on: windows-latest
    needs: ubuntu  # Runs after ubuntu
    steps:
      - name: Check if Key Vault Exists
        shell: pwsh
        run: |
          Write-Host "##vso[task.setvariable variable=resourceExists]true"
      - run: date
      - name: Display Key Vault Properties
        shell: pwsh
        run: |
          Write-Output "Key Vault Properties:"
          Write-Output "test properties"

      # Infrastructure task within the Windows job
      - name: Infrastructure Functions - Create Key Vault
        shell: pwsh
        run: |
          # Conditionally create Key Vault if resourceExists is false
          if ($env:resourceExists -eq "false") {
            Write-Output "Creating Key Vault..."
            # Add key vault creation logic here
          } else {
            Write-Output "Key Vault already exists, skipping creation."
          }

      - name: Display Key Vault Resource Existence Status
        shell: pwsh
        run: |
          Write-Output "resourceExists:"
          Write-Output "$env:resourceExists"

  macos:
    runs-on: macos-latest
    needs: [ubuntu, windows]  # Runs after ubuntu and windows jobs
    steps:
      - run: date
